export const ERROR_MESSAGES = {
  PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  USERNAME_ALREADY_TAKEN: "USERNAME_ALREADY_TAKEN",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INVALID_NEW_PASSWORD: "INVALID_NEW_PASSWORD",
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",
  EMAIL_ALREADY_USED: "EMAIL_ALREADY_USED",
};
